### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by dev-master21** [erictemponi/mod-antifarming#1]
![image](https://user-images.githubusercontent.com/16816228/71771505-450ef800-2f66-11ea-8344-53fdaeaf0140.png)
last rev azerothcore

**Comment by erictemponi** [comment]
Solved

**Comment by dev-master21** [comment]
![image](https://user-images.githubusercontent.com/16816228/71779977-a5de1500-2fe6-11ea-9217-fe4fdabf85ac.png)

**Comment by erictemponi** [comment]
I used clang++ to compile it and fixed the "fatal errors", now it should compile without any errors.
