### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by htc16** [erictemponi/mod-antifarming#2]
![image](https://user-images.githubusercontent.com/58153179/139449166-836ba02b-cc4a-447f-b99e-762356bee387.png)

**Comment by htc16** [comment]
Solution: 

#if AC_COMPILER == AC_COMPILER_GNU
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

using namespace Acore::ChatCommands;

**Comment by erictemponi** [comment]
Fixed by new commit
